apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-meditation-agent
  labels:
    app: focus-meditation-agent
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: focus-meditation-agent
  template:
    metadata:
      labels:
        app: focus-meditation-agent
        version: v1
    spec:
      containers:
      - name: focus-meditation-agent
        image: bilalrazaswe/focus-meditation-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
