apiVersion: v1
kind: Service
metadata:
  name: focus-meditation-agent-nodeport
  labels:
    app: focus-meditation-agent
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: focus-meditation-agent
  sessionAffinity: None
